#!/usr/bin/env node
/**
 * Write a source.sh beside a film that re-downloads exactly the photographs it
 * uses, with their credits, so a film can be shared or committed without its
 * media folder.
 *
 *   node scripts/lock.mjs <project>/film.json
 *   bash <project>/source.sh        # on another machine, from an empty folder
 */
import { readFileSync, writeFileSync, chmodSync } from 'node:fs';
import { dirname, join, resolve, basename } from 'node:path';

const filmPath = resolve(process.argv[2] || '');
if (!process.argv[2]) { console.error('usage: lock.mjs <film.json>'); process.exit(1); }
const dir = dirname(filmPath);
const film = JSON.parse(readFileSync(filmPath, 'utf8'));
const credits = JSON.parse(readFileSync(join(dir, 'media', 'credits.json'), 'utf8'));
const by = Object.fromEntries(credits.map((c) => [c.file, c]));
const used = [...new Set(film.shots.filter((s) => s.src).map((s) => basename(s.src)))];

const missing = used.filter((f) => !by[f]?.image);
if (missing.length) { console.error(`no source URL recorded for: ${missing.join(', ')}`); process.exit(1); }

const q = (s) => `'${String(s).replace(/'/g, `'\\''`)}'`;
const lines = [
  '#!/usr/bin/env bash',
  '# Fetch the photographs this film uses into ./media, with their credits.',
  '# Generated by scripts/lock.mjs. Run from anywhere: bash source.sh',
  'set -euo pipefail',
  'cd "$(dirname "$0")"',
  'mkdir -p media',
  'UA="horizon-reel/0.1 (+https://github.com/misbahsy/claude-horizon-animation)"',
  'fetch() { [ -f "media/$1" ] || curl -sSL --fail -A "$UA" -H "AIC-User-Agent: $UA" -o "media/$1" "$2"; echo "  $1"; }',
  ...used.map((f) => `fetch ${q(f)} ${q(by[f].image)}`),
  "cat > media/credits.json <<'JSON'",
  JSON.stringify(used.map((f) => by[f]), null, 2),
  'JSON',
  'echo "media ready: ${#} files"'.replace('${#}', String(used.length)),
];
const out = join(dir, 'source.sh');
writeFileSync(out, lines.join('\n') + '\n');
chmodSync(out, 0o755);
console.log(`${out}  ${used.length} images`);
